#http server
httpPort: 88
debug : true
jwtEncrtpy : jlkwdaa

#Mysql:
dbType: mysql
dbUser: root
dbHost: localhost:33006
dbPassword: 123456
dbName: AirLandCommand

# redis
redisAddr: localhost:6379
redisPassword: "123456"
redisDefaultDB: 0

# user
loginExpire: 73600

# Casbin角色模型的文件路径
rbacModelFilePath: conf/rbac_model.conf



